# @package eval.mmvet

handler: MultimodalBenchmarkEvaluator
output_dir: ${paths.output_dir}
overwrite: false
name: MM-Vet
benchmark: mmvet
format: json
data_path: ${paths.data_dir}/eval/mmvet/mm-vet.json
image_root: ${paths.data_dir}/eval/mmvet/images
processor_path: ${model.tokenizer_args.pretrained_model_name_or_path}
model_family: null
prompt_style: auto
generation_args:
  max_new_tokens: 128
  do_sample: false
max_samples: null
sample_seed: null
