model_handler: LlavaNextForConditionalGeneration
model_args:
  pretrained_model_name_or_path: "llava-hf/llava-v1.6-vicuna-7b-hf"
  torch_dtype: float16
tokenizer_args:
  pretrained_model_name_or_path: "llava-hf/llava-v1.6-vicuna-7b-hf"
  model_max_length: 4096
template_args:
  apply_chat_template: true
  system_prompt: ""
  user_start_tag: "USER: "
  user_end_tag: " "
  asst_start_tag: "ASSISTANT: "
  asst_end_tag: " "
